"""Add notification fields to StatusSwitch

Revision ID: 1c79df620bf5
Revises: 
Create Date: 2024-12-01 12:47:59.826808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c79df620bf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_switch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notification_text', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_switch', schema=None) as batch_op:
        batch_op.drop_column('notification_text')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
