"""Add email notification fields to Host model

Revision ID: 848cb1000414
Revises: 1c79df620bf5
Create Date: 2024-12-01 14:05:24.603868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848cb1000414'
down_revision = '1c79df620bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_emails', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_column('email_notifications_enabled')
        batch_op.drop_column('notification_emails')

    # ### end Alembic commands ###
